#!/bin/bash

cp ./.xinitrc ~/
cp ./.Xdefaults ~/
cp ./.bashrc ~/

cp ./wallpaper ~/Pictures/

cp -r ./config/bspwm ~/.config/
cp -r ./config/sxhkd ~/.config/
cp -r ./config/polybar ~/.config/
cp -r ./config/nvim ~/.config/
cp -r ./config/termite ~/.config/
