#!/bin/bash

# Installs WM config files based on arg 1
if [ ! -d ~/.config ]
then
    mkdir ~/.config
fi

if [ ! $# -eq 0 ]
then
    if [ $1 = "bspwm" ]
    then
        cp -r ./config/bspwm ~/.config/bspwm

        cp -r ./config/sxhkd ~/.config/sxhkd

        cp ./xinitrc/bspwm ~/.xinitrc
    elif [ $1 = "i3" ]
    then
        cp -r ./config/i3 ~/.config/i3

        cp ./xinitrc/i3 ~/.xinitrc
    elif [ $1 = "openbox" ]
    then
        cp ./xinitrc/openbox ~/.xinitrc
    fi
else
    echo "No window manager specified"
fi

# Copies Xresources and bashrc to /home

cp ./Xresources ~/.Xresources
cp ./bashrc ~/.bashrc

# Create Pictures Directory and add Wallpaper

if [ ! -d ~/Pictures ]
then
    mkdir -p ~/Pictures
fi

cp ./wallpaper ~/Pictures/

# Create Polybar Config Directory and File

cp -r ./config/polybar ~/.config/polybar

# Create Neovim Config Directory and File

cp -r ./config/nvim ~/.config/nvim

# Create Termite Config Directory and File

cp -r ./config/termite ~/.config/termite

# Create GTK3.0 Config Directory

cp -r ./config/gtk-3.0 ~/.config/gtk-3.0

# Create Icons Directory

cp -r ./icons ~/.icons
