#!/bin/bash

# Installs WM config files based on arg 1

if [ ! $# -eq 0 ]
then
    if [ $1 = "bspwm" ]
    then
        if [ ! -d ~/.config/bspwm ]
        then
            mkdir -p ~/.config/bspwm
        fi

        cp ./config/bspwm/* ~/.config/bspwm/

        if [ ! -d ~/.config/sxhkd ]
        then
            mkdir -p ~/.config/sxhkd
        fi

        cp ./config/sxhkd/* ~/.config/sxhkd/

        cp ./xinitrc/bspwm ~/.xinitrc
    elif [ $1 = "i3" ]
    then
        if [ ! -d ~/.config/i3 ]
        then
            mkdir -p ~/.config/i3
        fi

        cp ./xinitrc/i3 ~/.xinitrc
    elif [ $1 = "openbox" ]
    then
        if [ ! -d ~/.config/openbox ]
        then
            mkdir -p ~/.config/openbox
        fi

        cp ./xinitrc/openbox ~/.xinitrc
    fi
else
    echo "No window manager specified"
fi

# Copies Xresources and bashrc to /home

cp ./Xresources ~/.Xresources
cp ./bashrc ~/.bashrc

# Create Pictures Directory and add Wallpaper

if [ ! -d ~/Pictures ]
then
    mkdir -p ~/Pictures
fi

cp ./wallpaper ~/Pictures/

# Create Polybar Config Directory and File

if [ ! -d ~/.config/polybar ]
then
    mkdir -p ~/.config/polybar
fi

cp ./config/polybar/* ~/.config/polybar/

# Create Neovim Config Directory and File

if [ ! -d ~/.config/nvim ]
then
    mkdir -p ~/.config/nvim
fi

cp ./config/nvim/* ~/.config/nvim/

# Create Termite Config Directory and File

if [ ! -d ~/.config/termite ]
then
    mkdir -p ~/.config/termite
fi

cp ./config/termite/* ~/.config/termite/
cp ./config/gtk-3.0/* ~/.config/gtk-3.0/
