#!/bin/bash

cp ~/.xinitrc ./
cp ~/.Xdefaults ./
cp ~/.bashrc ./

cp ~/Pictures/wallpaper ./

cp ~/.config/bspwm/* ./config/bspwm/
cp ~/.config/sxhkd/* ./config/sxhkd/
cp ~/.config/polybar/* ./config/polybar/
cp ~/.config/nvim/* ./config/nvim/
cp ~/.config/termite/* ./config/termite/
