#!/bin/bash

# Installs WM config files based on arg 1

if ! [ $# -eq 0 ]
then
    if [ $1 = "bspwm" ]
    then
        cp -r ~/.config/bspwm ./config
        cp -r ~/.config/sxhkd ./config
        cp ~/.xinitrc ./xinitrc/bspwm
    elif [ $1 = "i3" ]
    then
        cp ~/.xinitrc ./xinitrc/i3
    elif [ $1 = "openbox" ]
    then
        cp ~/.xinitrc ./xinitrc/openbox
    fi
else
    echo "No window manager specified."
fi

# Updates Xresources and bashrc

cp ~/.Xresources ./Xresources
cp ~/.bashrc ./bashrc

# Update Current Wallpaper

cp ~/Pictures/wallpaper ./wallpaper

# Update Polybar Config

cp -r ~/.config/polybar ./config

# Update Neovim Config

cp -r ~/.config/nvim ./config

# Update Termite Config

cp -r ~/.config/termite ./config
cp -r ~/.config/gtk-3.0 ./config

cp -r ~/.icons/* ./icons/
