#! /bin/sh

sxhkd &

xrandr --output eDP1 --mode 1920x1080 --rate 60

feh --bg-tile ~/Pictures/wallpaper

polybar bspbar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            2
bspc config window_gap              20
bspc config top_padding             10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   true
